name: Linux

on:
  push:
  workflow_dispatch:

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4

    - run: sudo apt-get install -y ninja-build
    - run: pip install meson

    - run: meson setup build
    - run: meson compile -C build
    - run: build/hello

